### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=9; index=-3有的时候会报错

### ISSUE THREAD

**Issue by dfm899** [dinuscxj/EllipsizeTextView#6]
java.lang.ArrayIndexOutOfBoundsException: length=9; index=-3
	at android.text.StaticLayout.getLineStart(StaticLayout.java:857)
	at android.text.Layout.getLineExtent(Layout.java:955)
	at android.text.Layout.getLineWidth(Layout.java:943)
	at com.sj4399.terrariapeaid.app.widget.EllipsizeTextView.c(Unknown Source)
	at com.sj4399.terrariapeaid.app.widget.EllipsizeTextView.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:17628)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
	at android.view.View.measure(View.java:17628)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1294)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:17628)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
	at android.widget.LinearLayout.forceUniformWidth(LinearLayout.java:993)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:973)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
	at android.view.View.measure(View.java:17628)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
	at android.view.View.measure(View.java:17628)
	at android.support.v7.widget.RecyclerView$h.a(Unknown Source)
	at android.support.v7.widget.LinearLayoutManager.a(Unknown Source)
	at android.support.v7.widget.LinearLayoutManager.a(Unknown Source)
	at android.support.v7.widget.LinearLayoutManager.c(Unknown Source)
	at android.support.v7.widget.RecyclerView.J(Unknown Source)
	at android.support.v7.widget.RecyclerView.k(Unknown Source)
	at android.support.v7.widget.RecyclerView.onLayout(Unknown Source)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(Unknown Source)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2156)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1910)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6207)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
	at android.view.Choreographer.doCallbacks(Choreographer.java:612)
	at android.view.Choreographer.doFrame(Choreographer.java:581)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5689)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by dinuscxj** [comment]
fix 1.0.5
